mysite/photos/urls.py
from django.urls import path

from . import views
app_name="photos"
urlpatterns = [
    path('clear/', views.clear_database, name='clear_database'),
    path('basic-upload/', views.BasicUploadView.as_view(), name='basic_upload'),
    path('progress-bar-upload/', views.ProgressBarUploadView.as_view(), name='progress_bar_upload'),
    path('drag-and-drop-upload/', views.DragAndDropUploadView.as_view(), name='drag_and_drop_upload'),
]

mysite/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html')),
    path('photos/', include('mysite.photos.urls', namespace="photos")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/photos/models.py
from __future__ import unicode_literals

from django.db import models


class Photo(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='photos/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

mysite/photos/forms.py
from django import forms
from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file', )

mysite/photos/views.py
import time

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View

from .forms import PhotoForm
from .models import Photo


class BasicUploadView(View):
    def get(self, request):
        photos_list = Photo.objects.all()
        return render(self.request, 'photos/basic_upload/index.html', {'photos': photos_list})

    def post(self, request):
        form = PhotoForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save()
            data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


class ProgressBarUploadView(View):
    def get(self, request):
        photos_list = Photo.objects.all()
        return render(self.request, 'photos/progress_bar_upload/index.html', {'photos': photos_list})

    def post(self, request):
        time.sleep(1)  # You don't need this line. This is just to delay the process so you can see the progress bar testing locally.
        form = PhotoForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save()
            data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


class DragAndDropUploadView(View):
    def get(self, request):
        photos_list = Photo.objects.all()
        return render(self.request, 'photos/drag_and_drop_upload/index.html', {'photos': photos_list})

    def post(self, request):
        form = PhotoForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            photo = form.save()
            data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


def clear_database(request):
    for photo in Photo.objects.all():
        photo.file.delete()
        photo.delete()
    return redirect(request.POST.get('next'))

mysite/photos/templates/photos/base.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" action="{% url 'photos:clear_database' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-danger pull-right">
      <span class="glyphicon glyphicon-trash"></span> Clear Database
    </button>
  </form>
  <h1 class="page-header">
    Photos
    <small>/ {% block title %}{% endblock %}</small>
  </h1>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Examples</h3>
        </div>
        <div class="list-group">
          <a href="{% url 'photos:basic_upload' %}" class="list-group-item{% if request.path == '/photos/basic-upload/' %} active{% endif %}">
            Basic Upload
          </a>
          <a href="{% url 'photos:progress_bar_upload' %}" class="list-group-item{% if request.path == '/photos/progress-bar-upload/' %} active{% endif %}">
            Progress Bar Upload
          </a>
          <a href="{% url 'photos:drag_and_drop_upload' %}" class="list-group-item{% if request.path == '/photos/drag-and-drop-upload/' %} active{% endif %}">
            Drag and Drop Upload
          </a>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      {% block photos_content %}
      {% endblock %}
    </div>
  </div>
{% endblock %}

mysite/photos/templates/photos/basic_upload/index.html
{% extends 'photos/base.html' %}

{% load static %}

{% block title %}Basic Upload{% endblock %}

{% block javascript %}
  {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'photos/js/basic-upload.js' %}"></script>
{% endblock %}

{% block photos_content %}
  <div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
    </button>
    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'photos:basic_upload' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>

  <table id="gallery" class="table table-bordered">
    <thead>
      <tr>
        <th>Photo</th>
      </tr>
    </thead>
    <tbody>
      {% for photo in photos %}
        <tr>
          <td><a href="{{ photo.file.url }}">{{ photo.file.name }}</a></td>
          <td>{{photo.title}}</td>
          <td><img src="{{photo.file.url }}" style="width:150px; height:auto;"></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

mysite/photos/templates/photos/drag_and_drop_upload/index.html
{% extends 'photos/base.html' %}

{% load static %}

{% block title %}Drag and Drop Upload{% endblock %}

{% block javascript %}
  {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'photos/js/drag-and-drop-upload.js' %}"></script>
{% endblock %}

{% block photos_content %}
  <div class="well text-muted text-center" style="padding-top: 4rem; padding-bottom: 4rem;">
    <span class="glyphicon glyphicon-arrow-down" style="font-size: 4rem;"></span>
    <h3>Drop Photos Here to Upload</h3>
  </div>

  <input id="fileupload" type="file" name="file" multiple
         style="display: none;"
         data-url="{% url 'photos:basic_upload' %}"
         data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>

  <table id="gallery" class="table table-bordered">
    <thead>
      <tr>
        <th>Photo</th>
      </tr>
    </thead>
    <tbody>
      {% for photo in photos %}
        <tr>
          <td><a href="{{ photo.file.url }}">{{ photo.file.name }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

mysite/photos/templates/photos/progress_bar_upload/index.html
{% extends 'photos/base.html' %}

{% load static %}

{% block title %}Progress Bar Upload{% endblock %}

{% block javascript %}
  {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'photos/js/progress-bar-upload.js' %}"></script>
{% endblock %}

{% block photos_content %}
  <div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos
    </button>
    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'photos:progress_bar_upload' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>

  <table id="gallery" class="table table-bordered">
    <thead>
      <tr>
        <th>Photo</th>
      </tr>
    </thead>
    <tbody>
      {% for photo in photos %}
        <tr>
          <td><a href="{{ photo.file.url }}">{{ photo.file.name }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Uploading...</h4>
        </div>
        <div class="modal-body">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mysite/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Photos Library - Simple is Better Than Complex{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
      .page-header {
        margin-top: 0;
      }
    </style>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="page-header">Multiple File Upload Example</h1>
  <p class="lead">See the example live clicking in the Photos menu.</p>
  <hr>
  <h2>Static Assets</h2>
  <p>Following the list of static assets used in this example</p>
  <ul>
    <li><a href="https://github.com/twbs/bootstrap/releases/tag/v3.3.7" target="_blank">Bootstrap 3.3.7</a></li>
    <li><a href="https://github.com/jquery/jquery/releases/tag/3.1.1" target="_blank">jQuery 3.1.1</a></li>
    <li><a href="https://github.com/blueimp/jQuery-File-Upload/releases/tag/v9.14.1" target="_blank">jQuery File Upload 9.14.1</a></li>
  </ul>
{% endblock %}

mysite/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% static 'home' %}">Photos Library</a>
    </div>
    <div class="collapse navbar-collapse" id="main-menu">
      <ul class="nav navbar-nav">
        <li{% if '/photos/' in request.path %} class="active"{% endif %}>
          <a href="/photos/basic-upload">Photos</a>
        </li>
        <li><a href="https://simpleisbetterthancomplex.com">simpleisbetterthancomplex.com</a></li>
      </ul>
    </div>
  </div>
</nav>